# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_trip_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtWidgets

class Ui_OtherWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(449, 290)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 50, 391, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(22)
        self.formLayout.setVerticalSpacing(25)
        self.formLayout.setObjectName("formLayout")
        self.tr_label_origin = QtWidgets.QLabel(self.formLayoutWidget)
        self.tr_label_origin.setObjectName("tr_label_origin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.tr_label_origin)
        self.to_input_destiny = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.to_input_destiny.setObjectName("to_input_destiny")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.to_input_destiny)
        self.tr_label_destiny = QtWidgets.QLabel(self.formLayoutWidget)
        self.tr_label_destiny.setObjectName("tr_label_destiny")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tr_label_destiny)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 170, 161, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.exit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tr_label_origin.setText(_translate("MainWindow", "Origem"))
        self.tr_label_destiny.setText(_translate("MainWindow", "Destino"))
        self.pushButton.setText(_translate("MainWindow", "Começar"))

    def exit(self):
        self.close()



if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_OtherWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
